/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import docente.Docente;
import docente.Gradoacademico;
import empleado.Empleado;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import personalAdministrativo.PersonalAdministrativo;

/**
 *
 * @author usuario
 */
public class GUI_1_Colegio extends javax.swing.JFrame {

  
    //Empleados
    Docente d1 =  new Docente("Delgado Savadera", "10064352",7, Gradoacademico.Doctorado,"");
    Docente d2 =  new Docente("Efrain Vazquez", "10067544",2, Gradoacademico.Magister,"");
    Docente d3 =  new Docente("Viviana Gomez", "10067549",10, Gradoacademico.Doctorado,"");
    Docente d4 =  new Docente("Joshua Madrid", "10065689",50, Gradoacademico.Doctorado,"");
    Docente d5 =  new Docente("Roosvelt Antonio", "10027803",0, Gradoacademico.Magister,"");      
    PersonalAdministrativo p1 = new PersonalAdministrativo("Erika Vanesa", "1241414","Recursos Humanos","");
    PersonalAdministrativo p2 = new PersonalAdministrativo("Fabian Gomez", "100012313","Bienestar Universitario","");
    PersonalAdministrativo p3 = new PersonalAdministrativo("carlos Aguirre", "235534645"," Rectoia","");
    PersonalAdministrativo p4 = new PersonalAdministrativo("Daniel Cardona", "100643244"," Jefe Departamental","");
    PersonalAdministrativo p5 = new PersonalAdministrativo("Laura Giraldo", "1012340805","Secretaria","");
    
    ArrayList <Empleado> listaEmpleados = new ArrayList<>();
    
    String seleccionadoDocente,SeleccionadoPersonalAdmin;
    
    public GUI_1_Colegio() {
            
            listaEmpleados.add(d1);
            listaEmpleados.add(d2);
            listaEmpleados.add(d3);
            listaEmpleados.add(d4);
            listaEmpleados.add(d5);            
            listaEmpleados.add(p1);
            listaEmpleados.add(p2);
            listaEmpleados.add(p3);
            listaEmpleados.add(p4);
            listaEmpleados.add(p5);
            
            
            
            
            
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Profesores = new javax.swing.JComboBox<>();
        AsignarMateria = new javax.swing.JButton();
        MateriasDisponibles = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        PersonalAdmin = new javax.swing.JComboBox<>();
        TecnologiaDisponible = new javax.swing.JComboBox<>();
        AsignarTecnologia = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        HistorialAsignaciones = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Profesores.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Delgado Savadera", "Efrain Vazquez", "Viviana Gomez", "Joshua Madrid", "Roosvelt Antonio" }));
        Profesores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProfesoresActionPerformed(evt);
            }
        });

        AsignarMateria.setText("-->");
        AsignarMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AsignarMateriaActionPerformed(evt);
            }
        });

        MateriasDisponibles.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Discretas ll", "Discretas l", "Programacion Interactiva", "Ingles l", "Ingles ll", "ingles ll", "Calculo lll", "Calculo ll", "Calculo l", "Fuentes l", "Matematica Financiera", " " }));

        jLabel2.setText("Profesores");

        jLabel3.setText("Materias Disponible");

        jLabel4.setText("Asignar");

        jLabel5.setText("Personal Administrativo");

        PersonalAdmin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Erika Vanesa", "Fabian Gomez", "carlos Aguirre", "Daniel Cardona", "Laura Giraldo" }));
        PersonalAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PersonalAdminActionPerformed(evt);
            }
        });

        TecnologiaDisponible.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Office", "World", "Power Point", "Excel", " " }));
        TecnologiaDisponible.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TecnologiaDisponibleActionPerformed(evt);
            }
        });

        AsignarTecnologia.setText("-->");
        AsignarTecnologia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AsignarTecnologiaActionPerformed(evt);
            }
        });

        jLabel6.setText("Asignar");

        jLabel7.setText("Tecnologias disponible");

        jButton1.setText("FinalizarAsignaciones");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        HistorialAsignaciones.setColumns(20);
        HistorialAsignaciones.setRows(5);
        jScrollPane1.setViewportView(HistorialAsignaciones);

        jLabel8.setText("Historial Asignaciones");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setText("Personal Adimnistrativo");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setText("Docentes");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel11.setText("Colegio");

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(242, 242, 242)
                        .addComponent(jLabel11))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(PersonalAdmin, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Profesores, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel2))
                                        .addGap(52, 52, 52)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel4)
                                            .addComponent(AsignarMateria, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(64, 64, 64)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel7)
                                    .addComponent(MateriasDisponibles, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(52, 52, 52)
                                .addComponent(jLabel6))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(167, 167, 167)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(178, 178, 178)
                                .addComponent(AsignarTecnologia, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(64, 64, 64)
                                .addComponent(TecnologiaDisponible, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel9)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 481, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(17, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(193, 193, 193))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(75, 75, 75))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(35, 35, 35))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(18, 18, 18)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Profesores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AsignarMateria)
                            .addComponent(MateriasDisponibles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(PersonalAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(AsignarTecnologia)
                        .addComponent(TecnologiaDisponible, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18))
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jSeparator2)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        JOptionPane.showMessageDialog(null,"                 Resumen Asignaciones\n\n"+ HistorialAsignaciones.getText());
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void ProfesoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProfesoresActionPerformed
        if(evt.getSource() == Profesores){
            seleccionadoDocente = (String) Profesores.getSelectedItem();
        }
    }//GEN-LAST:event_ProfesoresActionPerformed

    private void AsignarMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AsignarMateriaActionPerformed
       String infoDoc = "";
        for(Empleado emp : listaEmpleados) {
            if(emp.getNombre().equals(seleccionadoDocente)){
                String tipoemp = emp.getClass()+"";
              if(tipoemp.equals("class docente.Docente")){
                  Docente doc = (Docente) emp;
              String materiaSelec = (String) MateriasDisponibles.getSelectedItem();
              doc.setAsignatura(materiaSelec);
              infoDoc = doc.GetInfo();
             
            }
            }
             
        }
        String textoant = HistorialAsignaciones.getText();
        HistorialAsignaciones.setText(textoant + infoDoc + "\n");
           
    }//GEN-LAST:event_AsignarMateriaActionPerformed

    private void PersonalAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PersonalAdminActionPerformed
       if(evt.getSource()==PersonalAdmin){
           SeleccionadoPersonalAdmin = (String) PersonalAdmin.getSelectedItem();
       }
    }//GEN-LAST:event_PersonalAdminActionPerformed

    private void AsignarTecnologiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AsignarTecnologiaActionPerformed
        String infoPer = "";
        for (Empleado emp :listaEmpleados) {
            if(emp.getNombre().equals(SeleccionadoPersonalAdmin)){
                String tipoemp = emp.getClass()+"";
              if(tipoemp.equals("class personalAdministrativo.PersonalAdministrativo")){
                  PersonalAdministrativo perAdmin = (PersonalAdministrativo) emp;
              String tecnologiaSelec = (String) TecnologiaDisponible.getSelectedItem();
              perAdmin.setTecnologiasManejadas(tecnologiaSelec);
              infoPer = perAdmin.GetInfo();
             
            }
            }
        }
        
        String textoant = HistorialAsignaciones.getText();
        HistorialAsignaciones.setText(textoant + infoPer + "\n");
        
    }//GEN-LAST:event_AsignarTecnologiaActionPerformed

    private void TecnologiaDisponibleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TecnologiaDisponibleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TecnologiaDisponibleActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_1_Colegio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_1_Colegio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_1_Colegio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_1_Colegio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI_1_Colegio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AsignarMateria;
    private javax.swing.JButton AsignarTecnologia;
    private javax.swing.JTextArea HistorialAsignaciones;
    private javax.swing.JComboBox<String> MateriasDisponibles;
    private javax.swing.JComboBox<String> PersonalAdmin;
    private javax.swing.JComboBox<String> Profesores;
    private javax.swing.JComboBox<String> TecnologiaDisponible;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables
}
